# Generated by Django 4.2.1 on 2023-06-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_github_user_linkedin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Data inicial')),
                ('end_date', models.DateTimeField(verbose_name='Data final')),
            ],
        ),
    ]
