# Generated by Django 4.2.1 on 2023-06-14 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_projectsdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectsdate',
            options={'verbose_name': 'prazo', 'verbose_name_plural': 'prazos'},
        ),
        migrations.AlterModelTable(
            name='projectsdate',
            table='prazos',
        ),
    ]
