# Generated by Django 4.2.1 on 2023-06-14 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_projectsdate_options_alter_projectsdate_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectsdate',
            options={'verbose_name': 'prazo'},
        ),
        migrations.AlterModelTable(
            name='projectsdate',
            table='prazo',
        ),
    ]
