# Generated by Django 4.2.1 on 2023-06-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_projectsdate_options_alter_projectsdate_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsdate',
            name='end_date',
            field=models.DateTimeField(null=True, verbose_name='Data final'),
        ),
        migrations.AlterField(
            model_name='projectsdate',
            name='start_date',
            field=models.DateTimeField(null=True, verbose_name='Data inicial'),
        ),
    ]
