# Generated by Django 4.2.1 on 2023-06-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_idea_explanation_projectsideas_explanation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsideas',
            name='stack',
            field=models.CharField(max_length=255, null=True, verbose_name='Stack'),
        ),
    ]
