# Generated by Django 4.2.1 on 2023-06-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_projectsideas_stack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsideas',
            name='level',
            field=models.CharField(choices=[('1', 'Fácil'), ('2', 'Médio'), ('3', 'Difícil')], max_length=255, verbose_name='Nível'),
        ),
        migrations.AlterField(
            model_name='projectsideas',
            name='stack',
            field=models.CharField(choices=[('1', 'Backend'), ('2', 'Frontend'), ('3', 'Fullstack')], max_length=255, null=True, verbose_name='Stack'),
        ),
    ]
