# Generated by Django 4.2.1 on 2023-06-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_projectsideas_level_alter_projectsideas_stack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsideas',
            name='end_date',
        ),
        migrations.AlterField(
            model_name='projectsideas',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data inicial'),
        ),
    ]
