# Generated by Django 4.2.2 on 2023-06-30 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_alter_project_is_inspired'),
        ('users', '0012_rename_projectsideas_projectidea_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectIdea',
        ),
    ]
