# Generated by Django 4.2.1 on 2023-05-23 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='project',
            table='projects',
        ),
    ]
