# Generated by Django 4.2.1 on 2023-05-24 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
    ]
