# Generated by Django 4.2.1 on 2023-05-24 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_rename_user_comment_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='date_updated',
            new_name='updated_at',
        ),
    ]
