# Generated by Django 4.2.1 on 2023-06-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_remove_project_description_project_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='subtitle',
            field=models.CharField(max_length=100, verbose_name='Subtítulo'),
        ),
    ]
