# Generated by Django 4.2.1 on 2023-06-24 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_projectsideas'),
        ('projects', '0011_alter_project_explanatory_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_inspired',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.projectsideas', verbose_name='Inspirado em'),
        ),
    ]
