# Generated by Django 4.2.1 on 2023-06-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_project_is_inspired'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='stack',
            field=models.CharField(max_length=255, null=True, verbose_name='Stack utilizada'),
        ),
    ]
