# Generated by Django 4.2.3 on 2023-07-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_complaint_project_complaints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='complaints',
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
        migrations.AddField(
            model_name='project',
            name='complaints',
            field=models.IntegerField(blank=True, null=True, verbose_name='Denúncias'),
        ),
    ]
