# Generated by Django 4.2.3 on 2023-07-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_remove_project_complaints_delete_complaint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='complaints_notifications',
            field=models.IntegerField(blank=True, null=True, verbose_name='Notificação de denúncia'),
        ),
    ]
