# Generated by Django 4.2.3 on 2023-07-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_project_complaints_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='complaints',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Denúncias'),
        ),
        migrations.AlterField(
            model_name='project',
            name='complaints_notifications',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Notificação de denúncia'),
        ),
    ]
