# Generated by Django 4.2.3 on 2023-07-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_alter_project_complaints_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='Publicado'),
        ),
    ]
