# Generated by Django 4.2.3 on 2023-07-20 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_alter_project_image'),
        ('projects', '0022_alter_project_complaints_and_more'),
    ]

    operations = [
    ]
